project_id = "osewboiklhfiunetoxzo"

[functions.crm-n8n]
verify_jwt = false

[functions.auto-promotion]
verify_jwt = false

[functions.generate-report]
verify_jwt = false

[functions.public-order]
verify_jwt = false
